### ISSUE TITLE
No scrap metal container available

### ISSUE THREAD

**Issue by tfischer4765** [taniwha/Extraplanetary-Launchpads#101]
Currently, no dedicated container to hold scrap metal is available in the mod. The only part that can store scrap metal is the smelter itself. I can't build a small rover or orbiter to scoop up trash and then take it to a larger station to be processed.

**Comment by davidson16807** [comment]
I posted some progress on this on a duplicate issue, #133

**Comment by taniwha** [comment]
I've merged @davidson16807 's PR for this.
