### ISSUE TITLE
Connector nodes to build directly onto existing parts

### ISSUE THREAD

**Issue by tfischer4765** [taniwha/Extraplanetary-Launchpads#103]
Some parts are simply too big to move around with KAS because it would take fifty or more kerbals to move them. I came across this when building bases with the civilian management mod that has some truely gargantuan parts, but even larger engines or tanks can run into the tens of tons and would require a truckload of kerbals to move.

 The idea is to have a node-attachable KAS compatible placeholder part that acts like a survey stake, only the new construction ends up attached to the node the placeholder was attached to, replacing it. There could be a counterpart that marks the node by which the new construction is supposed to be attached.

**Comment by sardia** [comment]
This is due to KIS, not KAS. Have you tried increasing the strength of the kerbals in the KIS settings.cfg file? Change the grabmaxmass (in tons) from 1 to whatever is appropriate, I did 5 tons so a command crew of 3 could lift most things. I also increased the grab distance so I didn't have to herd cats to get all the EVA crew near a part.
Alternately, aren't you suppose to use winches to life heavy things?
EvaPickup
	{
		grabKey = g	
		attachKey = h	
		allowPartAttach = false
		allowStaticAttach = false
		allowSnapAttach = false
		maxDistance = 3
		grabMaxMass = 1

**Comment by tfischer4765** [comment]
Interesting ideas, to be sure, but they do feel a little cheaty if you don't mind my saying so. The problem with winches is that while I can _move_ things with them, I still need to bring enough kerbals together to lift things to _attach_ it anywhere, because a winch won't count against kerbals needed to lift things. (I think I created a ticket to that effect in the KIS/KAS github as well)

**Comment by sardia** [comment]
Unfortunately, there's not a good way to approximate using tools/heavy equipment as a way to increase the carrying capacity of a kerbal. There's also not a good way to bring a bunch of kerbals together.  Try increasing the grab mass to 2 tons, you'll be glad you did.

**Comment by tfischer4765** [comment]
Thanks for the hint, I'll do just that for now. I'll still uphold the original suggestion, since it makes perfect sense for installations that have a manufacturing capability to build onto themselves or other craft directly. 

Also please check out the KAS github, I already shared some thoughts on how to tackle some of the problems intrinsic to using heavy equipment. The gist of it is, in a nutshell, to detect wether the part in question is attached to any grapling device and if it is, automatically increase the grab mass of kerbals within maxDistance tenfold. In essence exactly what you are suggesting, but at the same time adding some game mechanics.

**Comment by taniwha** [comment]
Implemented in 9d94adba22ec43ccbbd6bb7c87c50fbb2ed3c684
