### ISSUE TITLE
Bug: Inventory from launchpad2 is lost upon going EVA

### ISSUE THREAD

**Issue by tfischer4765** [taniwha/Extraplanetary-Launchpads#104]
Upon going EVA, the inventory of the Kerbals in the Launchpad2 module is lost. It can be stocked normally in the VAB and can be accessed normally via the inventory buttons while the Kerbals are still _in_ the module but once a Kerbal _leaves_ the module, his/her inventory is empty. If the Kerbal reenters the module, his or her inventory button does not reappear. If a Kerbal originally seated in another module is transferred to the Launchpad2, he/she loses his/her inventory, even if he is later transferred back. If a kerbal from a Launchpad2 seat is transferred into the seat vacated by said kerbal, he or she _acquires_ the inventory, in other words who transfers to the Launchpad2 module leaves his inventory in the original seat.

**Comment by taniwha-qf** [comment]
This is actually mostly a KIS bug (it requires an internal model to work). Fixing this properly needs to wait until I can handle internals. As a workaround, add the following to launchpad2's part.cfg:

INTERNAL {
    name = landerCabinInternals
}

There is already an INTERNAL node that has been commented out, so you can edit it suitably.

**Comment by GokouZWAR** [comment]
Will this same code work on the workshops also?

**Comment by tfischer4765** [comment]
I doubt it, since the workshop module seats a total of ten kerbals and the lander cabin seats only two. @taniwha-qf Proposed quick fix: reduce number of seats in workshop to eight, use the mk3 passenger module interior for now.

**Comment by GokouZWAR** [comment]
Just use a blank Iva...as long as it's there the rest is irrelevant. Having an interior would be nice for future but functionality is more important now. 10 kerbals are hard to get into a workshop anyway in career mode. They cost a lot anyway unless you're constantly going out rescuing kerbals all day long.

-GokouZWAR
