### ISSUE TITLE
Build cost in RocketParts should consider how much parts cost

### ISSUE THREAD

**Issue by alxhub** [taniwha/Extraplanetary-Launchpads#106]
Right now build cost is based on mass (among other things) which makes sense - bigger and denser things require more "stuff" to make them. But, that's not the only variable. Some mods add parts which are ludicrously expensive, costing millions of roots. Arguably, this is because they're deeply complex designs which are difficult to manufacture and require lots of precisely made components.

However, the RocketPart cost of these expensive parts is extremely low - comparable to a very "simple" part like a fuel tank of the same dry mass. This means that it's entirely too easy to farm money by constructing expensive parts off-world in very little time, then returning the finished products to the KSC.

Maybe this is by design, but I'd argue that the money cost should be a factor in the RocketPart construction cost calculated for all parts.

**Comment by taniwha-qf** [comment]
One of my design goals for EL is 100% independence from KSC. Once you own
the manufacturing chain (from resource extraction to final output),
"farming money" is unavoidable. Worrying about getting money quickly is
pretty pointless when we have timewarp, unless you're referring to time
relative to other events.

That said, this is why EL now has recipes: RocketParts is no longer
necessarily the only resource required to build a part. In fact,
RocketParts may not be required at all (the only reason it still is require
is to allow existing saves to continue).

Bill
-- 
Leave others their otherness. -- Aratak
There is no can't -- Duun

**Comment by alxhub** [comment]
I agree completely, and I'm not suggesting EL require money to build anything. I'm saying that the cost of a part is likely correlated to the difficulty of manufacturing it, and that should be taken into account by EL in the recipe somehow, either in terms of materials or build time required.

**Comment by taniwha** [comment]
Thus why the recipe system: it allows modders to tune EL's resource chain to their needs.
