### ISSUE TITLE
Orbital Dock Finalize Bug?

### ISSUE THREAD

**Issue by sardia** [taniwha/Extraplanetary-Launchpads#109]
When you create a ship, and it reaches 100%, I decided to tear it down instead of finalizing. I then decided to resume building, which quickly puts the dock back at 100% building. It will then bug out and refuse to give the option to finalize ship building.

Since KSP forums are down, I'll report it here. Is this a user error or a real bug?
http://i.imgur.com/DoLjd0b.png
![epl bug](https://cloud.githubusercontent.com/assets/16061847/11453499/17958542-95d2-11e5-8318-31ad011d82b9.jpg)

**Comment by taniwha** [comment]
I believe this has been fixed.
