### ISSUE TITLE
Unable to recycle a recycle bin

### ISSUE THREAD

**Issue by Hbas** [taniwha/Extraplanetary-Launchpads#110]
Version: http://taniwha.org/~bill/Extraplanetary_Launchpads_v5.2.94.zip

I´ve a station with a "small" recycle bin. When I tried to recycle a vessel with another recycle bin, the game slowed to a crawl then crashed in a few seconds. 

Pre-conditions (don't know if they are relevant or not):
- Have a station with a workshop, recycle bin (small), rocket and metal storage
- Have a ship with a recycle bin attached directly to the root part

Steps to reproduce:
1. Activate the station recycle bin and switch to the ship
2. Make sure the ship recycle bin is off
3. Approach the station´s recycle bin with the ship. (both recycles will be within 1m of each other)

Result: The game crashes.

Workaround:
- Using KIS, disassemble the recycle bin from the ship before approaching the station. The game now works as expected.

**Comment by taniwha** [comment]
I believe this is fixed in 5.2.95 by commit afe1760
