### ISSUE TITLE
Launch pad  GUI

### ISSUE THREAD

**Issue by zvergk** [taniwha/Extraplanetary-Launchpads#111]
I can't open the GUI. in  Launch pad. Because this button is not present in the list when I click on lauch pad or shipyard ( from UKS/OKS ). Button in toolbar is absent too. KSP 1.0.5 .EL 5.2.94.

**Comment by SarahLJP** [comment]
I'm encountering this same problem. KSP 1.1.3 EL 5.4.0

**Comment by taniwha** [comment]
Most likely an installation error. Please retry with either the latest EL (5.6.0) and KSP 1.2.2, or EL 5.2.95 if you're still using 1.0.5.
