### ISSUE TITLE
Can't attach survey stakes

### ISSUE THREAD

**Issue by foonix** [taniwha/Extraplanetary-Launchpads#113]
After updating KIS, I'm no longer able to hammer survey stakes to the ground.

http://i.imgur.com/z5FZRM1.png

KIS 1.2.5
EPL 5.2.95

Skimming the KIS source for the error, it looks like they added some checking on available nodes.  It falls back on surface attach node if none exist. 

I was able to work around this by setting `attachRules = 0,1,0,0,0` in the part.cfg.

**Comment by taniwha** [comment]
The correct fix is to use the ground-attach key (usually x). Survey stakes are by design not surface attachable.
