### ISSUE TITLE
Enhancement: Show *why* ship is not building when zero productivity

### ISSUE THREAD

**Issue by henrybauer** [taniwha/Extraplanetary-Launchpads#120]
Users often don't pay any attention to productivity, then wonder why they can't build anything.  The GUI could clue users in to this instead of sitting at 0% forever.  Two ideas below, but any GUI feedback would be welcome:
1. If you press "Build" and productivity is zero, pop up an error instead of progressing to the build window

2.The Build window could show a warning when productivity is zero (perhaps instead of the progress)

**Comment by taniwha** [comment]
Fixed by 9b7ccd7
