### ISSUE TITLE
Load Ship in UI causes peculiar fault

### ISSUE THREAD

**Issue by tea-man** [taniwha/Extraplanetary-Launchpads#121]
When selecting 'Load' from the EPL interface 'Select Vessel', the loaded vessel appears suddenly adjacent to the Launchpad/Orbital dock ship (while in orbit vessel appears at high velocity, testing on launchpad vessel appears stationary.) (edit: Contruscted vehicle is created adjacent to OrbitalDock at 0 velocity, rapidly receding from an orbital station)

The EPL interface does not recognise a vessel has been loaded and remains on the Dock Overview/select vessel screen.

This only occurs in a specific save - when a new save is started in sandbox this problem does not occur.  However all Orbital Docks/Launchpads both existing and new are affected.

While I'd like to fix the savefile due to the time I've invested, I suspect a module issue has hidden itself beyond my ability to spot, especially due to the number of mod updates during this save!

KSP.log and quicksave.sfs taken from shortly after launchpad test initiates fault.

[KSP.log.txt](https://github.com/taniwha/Extraplanetary-Launchpads/files/452581/KSP.log.txt)
[quicksave.sfs.txt](https://github.com/taniwha/Extraplanetary-Launchpads/files/452587/quicksave.sfs.txt)
[ModDirList.txt](https://github.com/taniwha/Extraplanetary-Launchpads/files/452605/ModDirList.txt)

**Comment by SamLex** [comment]
I also encountered this problem, and believe it is actually a bug in ContractConfigurator. Link to issue: [NRE in ReachState.CheckBiome](https://github.com/jrossignol/ContractConfigurator/issues/569).

**Comment by jrossignol** [comment]
I've made a change in Contract Configurator, but it's possible there's other mods or even stock code that doesn't handled a null Vessel.landedAt well.

**Comment by tea-man** [comment]
Well spotted SamLex, the updated ContractConfigurator binaries have solved this issue.
Many thanks to you both!
