### ISSUE TITLE
Recipies: Building from resources other than RocketParts is too fast

### ISSUE THREAD

**Issue by jd284** [taniwha/Extraplanetary-Launchpads#123]
When using recipies to change the construction materials (e.g. like MKS does to MaterialKits&SpecializedParts), construction is way too fast.
For some reason in Recipes/BuildResource.cs:KerbalHours(), everything but RocketParts is set to build 10x faster.
Is this meant to make converted resources such as SolidFuel or Ablator construct faster? In that case it should be done using a flag from BuildResource(Ingredient) only, and not by resource name.

**Comment by taniwha** [comment]
Yeah, this is a bug. The relevant code even has FIXME tags.
