### ISSUE TITLE
I can not build.

### ISSUE THREAD

**Issue by theemeraldwither** [taniwha/Extraplanetary-Launchpads#125]
It gives me all the options, but then it says 0% 0s and will not build

**Comment by taniwha** [comment]
Check your vessel productivity. It will be in the right-click menu of any command pod or workshop on the vessel. Vessel productivity must be greater than 0. For that, you need suitable engineers. Check the manual (EL_Manual.pdf)

**Comment by theemeraldwither** [comment]
But i had level five engineers with no stupidity in the construction things

**Comment by Furywalk** [comment]
I am having the same problem. I've tried changing the kerbals I have in my vessel and even edited the construction workshop to have 50 production. The moment I launch my productivity on all things, the workbench, command pods, and workshops, all have 0 production.

**Comment by theemeraldwither** [comment]
I never checked any of that but it wasn't working.  I will check if their
productivity is turning itself to 0.

**Comment by RaptorKing** [comment]
I have the same problem but I double check to be correct I see if I used the right parts and parts that are compatible and I had rocket parts and that I had a productivity of over 1 and it still did't work and even after I downloaded over again it still didn't work so my only assumption is that the mod is broken or needs to have further examinations in the files.

**Comment by theemeraldwither** [comment]
The thing i dont get is Toxic Timewaster uses it in his Super Colonization series and Kottabos Games used it in a mod showcase.

**Comment by theemeraldwither** [comment]
does this mod have any dependencies

**Comment by theemeraldwither** [comment]
I am sad about this.  I really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really really really really really really really really
really really really wanted this mod.  :(

**Comment by RaptorKing** [comment]
I know it make 0 sense why would it work their but not here its the same
game update every thing toxic timewaster even states he uses it in the
latest update even though it dose not work even thought he stopped super
colonization his last video was in 1.2.1 it should still work after one up
date nothing new but bug fixes.

**Comment by theemeraldwither** [comment]
Taniwaha, plz plz plz plz plz plz plz plz plz plz fix the mod

**Comment by theemeraldwither** [comment]
I really want to use it

**Comment by theemeraldwither** [comment]
I've run out of things to do in KSP and this will make me start playing
again

**Comment by theemeraldwither** [comment]
PLZ PLZ PLZ PLZ PLZ FIX IT!!!!!!!!!!!!!!

**Comment by SpaceCoreInSpace** [comment]
I can't build either and theirs one thing I noticed in career after I leveled up my engineer, instead of the production going up it went to -3 so I don't know if something went wrong in the programming in it cause it barely works in sandbox with a level five engineer its 0.1 production if this helps to fix this bug, your welcome I guess I don't know what to say after that...

**Comment by AstroMec** [comment]
For me, it's even worse: I can't even build at all. It doesn't come up with a context menu if I right click the space dock. I guess it must be the way the folders are structured. PS: the big Hexa cans are often not loaded when I re-install this mod for updating.

**Comment by theemeraldwither** [comment]
I would start building a craft but it would stay at 0% forever and would
not give me an estimated time.

**Comment by taniwha** [comment]
Likely due to lack of productivity. Closing due to the spammy messages.
