### ISSUE TITLE
Ship parts not converting to metal when recycled

### ISSUE THREAD

**Issue by GokouZWAR** [taniwha/Extraplanetary-Launchpads#128]
For some reason the small recycle does not properly convert a part into metal when recycled. I recycled an entire ship, all fuel and resources were transferred but I received zero metal from the ship. (There was plenty of space in the container which I expected to be full and then some when the ship was recycled, but it remained at the same level throughout the recycling process). I tested a few smaller parts like nosecones and lights as well and nothing was recycled into metal. Am I missing something? Using version 5.7.1. (I saw no notes that this was fixed in 5.7.2 so I didn't bother updating, a side note CKAN does not have 5.7.2 at this moment).

**Comment by GokouZWAR** [comment]
Confirmed that this issue was not present in version 5.6.0. I rolled back to 5.7.0 and it still did not recycle properly, so i rolled back to 5.6.0 and the recycler properly recycled the same part i was testing with in 5.7.1's version.

**Comment by taniwha** [comment]
Sorry about the delay. This was a deliberate change between 5.6.0 and 5.7.0: recyclers now convert parts to ScrapMetal instead of Metal. This is easily tweaked by editing the recycle recipe for RocketParts (in GameData/ExtraplanetaryLaunchpads/Resources/Recipes.cfg

**Comment by taniwha** [comment]
Oh, if there is a bug, it's the lack of ScrapMetal containers.
