### ISSUE TITLE
No containers for Scrap metal

### ISSUE THREAD

**Issue by OrionKaelin** [taniwha/Extraplanetary-Launchpads#133]
No containers for Scrap metal which a recycle outputs when in use.
The only part that can hold scrap metal is a smelter which is far to small for even small recycling jobs and is impractical to use on smaller probes or rovers.

**Comment by davidson16807** [comment]
I have a branch out on my fork that tries to address this, named "scap-canisters". I haven't tested the functionality yet, and I still need to create unique textures, but I think I've gotten the hang of the .mbm format well enough that I can add it. 

@taniwha: what color would you like the canisters? Green hasn't been taken yet.

**Comment by davidson16807** [comment]
Update: I've retextured the scrap canisters green. I'm going to test out these changes later tonight.

**Comment by taniwha** [comment]
I've meged @davidson16807 's PR for this.
