### ISSUE TITLE
Crash on Finalize with Principia Mod

### ISSUE THREAD

**Issue by jfcroft245** [taniwha/Extraplanetary-Launchpads#137]
Hi Guys,

Loving the mod!

I am playing KSP 1.4.1 with the SimpleConstruction configuration pack which contains the latest EL (5.9.0). I am also using Principia Mod (2018-03-17).

When I finalise a build on a EL Launchpad the game crashes to desktop. I have attached the crash report from Principia which seems to be causing the crash. 

The error given in the report is the same as a bug that was reported on Principia a while ago. The player would get a crash when attaching something using KIS. I think a similar thing is happening here when the craft is spawned by EL. Principia finds a vessel without parts and kicks up a fuss.

[Link](https://github.com/mockingbirdnest/Principia/issues/1549)

Would love to see a patch for this, definitely would deserve beer money! Let me know if you need any more info.

Regards,

jfcroft245

[ERROR.20180325-003141.5800.zip](https://github.com/taniwha/Extraplanetary-Launchpads/files/1845297/ERROR.20180325-003141.5800.zip)

**Comment by taniwha** [comment]
EL does not create vessels without parts. When finalizing a build, EL creates vessels using ShipConstruction.AssembleForLaunch(), which is exactly the same method stock KSP uses when launching a new vessel. That you got as far as finalizing the build indicates that EL's other vessel creation method (used for calculating build costs) does not cause Principia to crash. The only effective difference is the cost calculation vessel does not survive the frame.

More information is needed as to what sort of finalization is being done: docked builds (launchpad/orbital dock) and survey builds do different things to the created vessel.

**Comment by taniwha** [comment]
Closing due to lack of further information.
