### ISSUE TITLE
Issues with 6.0.0

### ISSUE THREAD

**Issue by mortuux** [taniwha/Extraplanetary-Launchpads#138]
I'm no longer able to build using the K&K Launchpad, it won't even show up as an option in the UI. Regarding the orbital construction dock and disposable pad, they show up in the UI but tells me I have no productivity. It worked fine before the update. I have workshops and people in them, and I have plenty of parts and fuel. Not sure what the problem is if there's anyway you could help it'd be greatly appreciated.

**Comment by mortuux** [comment]
Sorry I'm a little slow at the moment, day off after working a lot. Is this an issue I need to resolve or is it a waiting game?

**Comment by LouisCyfer** [comment]
[PR #139](https://github.com/taniwha/Extraplanetary-Launchpads/pull/139) might solve it.
additionally you might wanna look into my attempt to update KBPS' EL support [here](https://github.com/LouisCyfer/KSP-funTweaks/tree/master/EL6.0_mod-compatiblity/GameData) and some other mods.

This might just yet be inclomplete and suggestions & feedback is always welcome!

**Comment by RaaviArda** [comment]
When building and launching a new ship on launch pad (both small and large) the optional resources such as fuel are taken from the origin base but not transferred to the new ship.
Before construction: Launch pad has 306 liquid fuel, base has another 1440
Construction finished and finalized: no change
Release: Launch pad has 306 LF, base has 1350 (-90, as expected), new craft has 0
Same goes for oxidizer but energy gets transferred correctly

**Comment by taniwha** [comment]
@RaaviArda please don't mix up issues.

Closing as this seems to have been resolved.
