### ISSUE TITLE
6.0.0 - Tearing Down / Cancelling a build can cause crashes / kraken

### ISSUE THREAD

**Issue by MrKiel** [taniwha/Extraplanetary-Launchpads#142]
I have been able to reproduce this fairly reliably. Log files included. 
The kraken occurs as the log is spammed with the error:
"Look rotation viewing vector is zero"

[KSP.log](https://github.com/taniwha/Extraplanetary-Launchpads/files/2066406/KSP.log)
[Player.log](https://github.com/taniwha/Extraplanetary-Launchpads/files/2066407/Player.log)

**Comment by taniwha** [comment]
Yup, this is a bug all right.
