### ISSUE TITLE
EPL completely non functional in newest version

### ISSUE THREAD

**Issue by Grave-Digger** [taniwha/Extraplanetary-Launchpads#150]
My EPL simply does not work. Some of the modules such as launchpads and workshops are missing. Orbital construction dock says "no more info" instead of showing the launchpad module, no gui for calculating rocketpart costs. I am unable to order the construction of a craft when in space. Any help is appreciated
![image](https://user-images.githubusercontent.com/44979187/52918888-55899600-32f4-11e9-8fd0-0c13c0c087d0.png)

**Comment by taniwha** [comment]
First, it is EL, not EPL: extraplanetary is one word (says so in the manual, too).

Second, I will need your KSP.log. You have an installation error and the easiest way for me to diagnose it is via the log file.

**Comment by taniwha** [comment]
Considering the timing of this issue, I suspect it to be the KAS update and so is probably fixed by commit 7c8e75a
