### ISSUE TITLE
Request: Make Extraplanetary Launchpads researchable

### ISSUE THREAD

**Issue by Monniasza** [taniwha/Extraplanetary-Launchpads#153]
I  suggest that Extraplanetary Launchpads be usable with carreer and science modes to create custom science vessels and launch them from space station.  It will help remove unnecessary parts from ships.

**Comment by taniwha** [comment]
It already is. Most of the stuff is in advanced construction.

**Comment by Monniasza** [comment]
However, many config files say "TechRequired = Unresearchable"

**Comment by taniwha** [comment]
Those are deprecated parts (or, in the case of the mallet, require KIS).
