### ISSUE TITLE
UI stops working after trying to load a craft with stock robotics 

### ISSUE THREAD

**Issue by patomartinsch** [taniwha/Extraplanetary-Launchpads#156]
Tried to load (not yet build) a craft with stock robotics parts and after getting an error saying there were some parts missing, the UI goes blank whenever I open it

**Comment by taniwha** [comment]
This is caused by the missing parts, not the robotic parts. I loaded one sub-assembly with missing parts and got the error, and another (actual craft, not just a sub-assembly) that had all parts available including a robotics part: no error.
