### ISSUE TITLE
UI don't show 

### ISSUE THREAD

**Issue by Bernadegas** [taniwha/Extraplanetary-Launchpads#158]
I am playing in 1.7.0, and after trying all the available versions of the mod, i've had the same problem. In the corrent version, 6.7.2, all the parts show up, but i can't access the UI. Nothing works, neither the normal parts, neither the kerbal invetory parts. I also have installed the Kerbal Planetary Base System, and the parts for this mod also don't work.
I have a lot of mods installed, and i dont no if they are causing this problem.

**Comment by taniwha** [comment]
For KSP 1.7.x, you need EL 6.6.2

**Comment by Bernadegas** [comment]
I have now updated to 1.7.3 version with the breaking ground DLC. The 6.6.2 version of the mod isn't working, it doesn't show all the parts neither the UI.

**Comment by taniwha** [comment]
Why not just update to 1.8 or 1.9? Things would be much easier.
