### ISSUE TITLE
EL UI Not Showing Up 

### ISSUE THREAD

**Issue by Gemmasterianksp** [taniwha/Extraplanetary-Launchpads#164]
I am using KSP 1.3.1 (yeah I know it's old) and there is no button at all for the build UI. The parts do load in and my output log shows correct load in from what I can tell of EL. My module manager is up to date and has only a single instance. I have deleted and redownloaded multiple times and I have even switched versions I am using (5.90 and then today 6.00 to see if it was a thing with that version). I am running a few dozen mods (about 12 gbs worth lol) so it could be that which I hope it isn't. I am unsure about what to do seeing as no output log error and I already made sure to do what the older threads said to do. None of the mods I have should effect this too, all of them are popular visual or part mods none of the underlying game rule rewriting mods like Principia or anything or that are really strange. Can give any info required.

**Comment by taniwha** [comment]
You need to use EL 5.9.0 (edit the version number in the download url). Note, however, that such old versions are no longer supported and you'll be on your own. You would be far better off updating your KSP to at least 1.8.1 (which is supported by the latest version of EL) as you will be missing out on a lot of improvements and bug fixes (476 commits' worth).

**Comment by Gemmasterianksp** [comment]
I have been using 5.9.0 I was just say that I used 6.0.0 once yesterday to see if it was a problem with 5.9.0 that could be fixed in 6.0.0.
