### ISSUE TITLE
Vessel Productivity is listed as 0

### ISSUE THREAD

**Issue by portalfan04** [taniwha/Extraplanetary-Launchpads#171]
Hi there, as well as getting issues to do with the UI (issue #129, latest comment) I am having problems with productivity on my bases. I am using version 6.8.3 on KSP 1.11.2. 

I have a base on Gilly, crewed by 2 max level engineers. I am using angel-125's pathfinder, so I am not sure if this is to do with that. The kerbals are in the inital boxed Ponderosa module that the mod provides, and it is listing their productivity as 0.48.... However, the vessel productivity is listed as 0. There are no other people on board my base, and nothing that should change anything. I have enough RocketParts as well. 

![screenshot13](https://user-images.githubusercontent.com/22401277/120045513-19335d00-c008-11eb-80cc-72dc01787da7.png)

https://github.com/taniwha/Extraplanetary-Launchpads/files/6563468/log.zip

**Comment by taniwha** [comment]
No longer relevant as the whole UI system has changed.
