### ISSUE TITLE
Launchpad needs Material Kits and Specialized Parts 

### ISSUE THREAD

**Issue by Koddra** [taniwha/Extraplanetary-Launchpads#172]
So i build my minmus base which can produce rocket parts and i thought that to build rockets i just need rocket parts but when i open up UI it shows that it needs material kits and specialized parts. Do i have to remove some mod for it to be just rocket parts? In other tutorials on youtube there are just rocket parts. I also haven't found any material kits or specialized parts in VAB. 

Image:  https://ctrlv.cz/VhHH

Image from tutorial youtube video:  https://ctrlv.cz/e4tV

**Comment by xDeerStalker** [comment]
That's a change by RoverDudes MKS mod. The corresponding Patch is found here:

Kerbal Space Program\GameData\UmbraSpaceIndustries\MKS\Patches\PatchManager\ActiveMMPatches\MKS_EL_Resources.cfg

Without warranty: If you move that file to your favorite backup location, EL should behave as expected while still having the additional workshops introduced by MKS.

**Comment by taniwha** [comment]
EL has a recipe system that allows other modders to define what resources are needed to build parts.
