### ISSUE TITLE
the button to "select craft" is greyed out, no matter how much rocket parts or materials i have. 

### ISSUE THREAD

**Issue by Pluto2077** [taniwha/Extraplanetary-Launchpads#174]
this occured after one time i tried to use the mod, the menu came up and i picked a craft, once i did the button greyed out and nothing ever came up, no option to actually build it. and now i cant even use it at all

**Comment by taniwha** [comment]
Selecting craft has nothing to do with how many rocket parts you have. This sounds like something went wrong with internal state. If you can reproduce this, please send a copy of KSP.log for the session.

**Comment by taniwha** [comment]
I'm pretty sure this was fixed with the flag textures.
