### ISSUE TITLE
Craft selection GUI broken in KSP 1.12.x

### ISSUE THREAD

**Issue by moss21** [taniwha/Extraplanetary-Launchpads#175]
It appears that the KSP 1.12.x craft select GUI is broken, as new ships cannot be selected or the button is simply greyed out.

KSP.Log attached, it should be at the bottom. 
[KSP.log](https://github.com/taniwha/Extraplanetary-Launchpads/files/7026270/KSP.log)

**Comment by taniwha** [comment]
This should be fixed in 6.99.0
