### ISSUE TITLE
spawning craft when Principia is installed

### ISSUE THREAD

**Issue by zer0Kerbal** [taniwha/Extraplanetary-Launchpads#176]
The other issue that @Carnasa(he talks about it here; is when spawning Extraplanetary-Launchpads constructed craft when Principia is installed and having to turn off gravity (hack gravity) in order to spawn without blowing up. No game crashes are involved.

(https://www.youtube.com/watch?v=bpa9lfMRWRE)

might be an idea to briefly 'pause' gravity altogether when spawning a build (finalize)

(https://github.com/mockingbirdnest/Principia/issues/3176)

**Comment by taniwha** [comment]
Please see if 6.99.1 improves the situation: commits e2e4ed1b75b49c71d176319664d9c3e348ef0086 and d1b10df5497efba44a28e55f7f466c995c4f9e5f seem to me to be highly relevant to this issue.

**Comment by taniwha** [comment]
@zer0Kerbal Well, is it fixed? A report of yes/no would be helpful.

**Comment by zer0Kerbal** [comment]
> @zer0Kerbal Well, is it fixed? A report of yes/no would be helpful.

I've heard nothing, which normally doesn't mean anything but could be considered a good sign. @taniwha

**Comment by taniwha** [comment]
Thanks I think I'll close these (there's another related issue). Principia users can issue a new one (or re-open) if it's not fixed.

**Comment by zer0Kerbal** [comment]
> Thanks I think I'll close these (there's another related issue). Principia users can issue a new one (or re-open) if it's not fixed.

thank you for looking into this. :D 
zed'K
