### ISSUE TITLE
survey stake not working right

### ISSUE THREAD

**Issue by Tommy7026** [taniwha/Extraplanetary-Launchpads#182]
![bug 4](https://user-images.githubusercontent.com/98718190/153779440-60a0ff06-97ce-468b-b5e2-81d2e8ce0913.PNG)
![bug 1](https://user-images.githubusercontent.com/98718190/153779442-23de6e23-2d35-4acc-891d-98657d4e8ea5.PNG)
![bug 2](https://user-images.githubusercontent.com/98718190/153779443-5f0eff6f-0887-4179-96c6-3d623cafa4b4.PNG)
![bug 3](https://user-images.githubusercontent.com/98718190/153779444-f0d06b46-392b-4c1c-a099-334514f01eaf.PNG)
![Kerbal Space Program Screenshot 2022 02 13 - 15 50 31 22](https://user-images.githubusercontent.com/98718190/153779450-0e8eb4a2-b9fc-42cb-a917-89a2e1b6c19b.png)
see screenshots so i dont have to ctrl-c ctrl-v a bunch of stuff here, the cone in question is a survey stake that's rover deployable and its from angel-125's sandcastle mod and as seen in the screenshots the bug was narrowed down to EL as opposed to sandcastle

**Comment by Tommy7026** [comment]
[KSP - no sudo crash.log](https://github.com/taniwha/Extraplanetary-Launchpads/files/8082788/KSP.-.no.sudo.crash.log)
[KSP - sudo crash compress.zip](https://github.com/taniwha/Extraplanetary-Launchpads/files/8082842/KSP.-.sudo.crash.compress.zip)
sudo crash was 30 mb so i compressed it via .zip

**Comment by zer0Kerbal** [comment]
was trying to record/illustrate how to use the stakes today - (SimpleConstruction (latest with latest launchpad.dll)) with latest Not So SimpleConstruction (adds the stakes))

all went well through stock - except when tried to press space to deploy - no joy.

seems to be related.

![Screen_Recorder17531_jShZy7S9w4](https://user-images.githubusercontent.com/39887717/171313860-764655b1-4a4a-455f-9d66-a27aa1701a1f.png)

![Screen_Recorder72767_bSirtzlxwa](https://user-images.githubusercontent.com/39887717/171313815-db69e851-42dd-438c-a8f3-71c6bdee060d.png)

**Comment by taniwha** [comment]
Any log spam is due to EL's parts not having ModuleCargoPart (or related).

Stakes will not behave properly with the stock inventory system. I do not know if I'll be able to fix that.

The missing stakes is possibly because KIS is not installed (though I fixed that in recent versions)

**Comment by zer0Kerbal** [comment]
understood. :D
