### ISSUE TITLE
ELPadView NREs

### ISSUE THREAD

**Issue by Rodg88** [taniwha/Extraplanetary-Launchpads#185]
On my station I've used multiple launchpads, and recycled some of them so they no longer exist, and a disposable pad. Now when I try to build a craft, the rotation buttons are gone saying 'no sites found', and there's ghost entries in the pads dropdown list. After I switch to the KSC, and back to the mothership, the list of pads is updated, and the rotate buttons are back, but trying to clear and restart a new build results in the 'no sites found' issue again
![image](https://user-images.githubusercontent.com/2611674/170682051-c0dd8bce-986b-43a5-ae65-be437754f58b.png)

NREs should come up when searching for `ELPadView`:

https://gist.github.com/Rodg88/7aec7152b7250fa5af6d576cba28da83

**Comment by Rodg88** [comment]
Like in #186 I have the same view of the UI https://media.discordapp.net/attachments/422839886337409042/981652521070231592/unknown.png

Another log from this occurrence, since it's slightly different from my initial report https://gist.github.com/Rodg88/c45b6adffd67cf75680fba3ec9b697e8

**Comment by taniwha** [comment]
This appears to be caused by a missing flag texture and EL not checking properly.
