### ISSUE TITLE
[v6.99.2] Craft built via survey station are offset off the surface

### ISSUE THREAD

**Issue by Rodg88** [taniwha/Extraplanetary-Launchpads#191]
Using a survey station, my craft gets built a few m above the origin defined by the stakes:
https://cdn.discordapp.com/attachments/837816252868722719/999934991414857788/unknown.png

On a normal launchpad, the craft is not offset, the base is spawned directly at the spawn transform.

**Comment by taniwha** [comment]
Fixed by b61b133
