### ISSUE TITLE
Creating contrainers with EL

### ISSUE THREAD

**Issue by Prototype2001** [taniwha/Extraplanetary-Launchpads#89]
Filled containers cost the same as empty containers. Crafting a container costs 300 rocket parts, contents within the container: 9000 rocketparts, EL just magically created 8700 rocket parts for free.

Edit: This can be done with C3 module, orbital shipyard, & mobile launch platform, pictures how to recreate this issue are posted near the bottom.

Edit2: Tested with latest 5.0.1, issue is still there.

**Comment by TraindKilla** [comment]
Are you referring to the KAS containers?

**Comment by Prototype2001** [comment]
MKS containers.

**Comment by Olympic1** [comment]
then report the issue on the MKS repo

**Comment by TraindKilla** [comment]
I don't have this issue when building KAS containers using EL. I get different values for containers with different contents. For example, a large container loaded with nothing but survey stakes costs me 50 rocket parts, whereas, a large container loaded with connector points and 2 ground pylon costs me 160 rocket parts. 

What container are you using that costs you 300 rocket parts?

**Comment by TraindKilla** [comment]
I'll download the FTT mod and mess around with it for a week or so and see if I can mimic your issue. For now ”self policing” may be an option until the issue can be investigated and resolved.

EL works great with the mods I mentioned above. If you see if fit, you could temporarily do away with the FTT mod and use these, if you are looking for a more ”realistic” experience. I don't own the EL mod or write the code dude. I'm just trying to help you out by telling you what works for me.

I'll let you know what happens after I get acquainted with the FTT mod. Best of luck to you for now. Touch back soon...

**Comment by Prototype2001** [comment]
I don't understand why you keep mentioning FTT when its not a FTT issue. Ore,metal, water, substrate, chemicals is not FTT its regolith, TAC LS food, oxygen is not FTT, yet EL ignores those resources when creating containers filled with them.

I said this several times FTT is not the issue.

**Comment by Olympic1** [comment]
Well Regolith doesn't add resources (only Rock) it is CRP and MKS that add those resources.

But I'll try to repro this with EL, KAS and all USI. Are you using more mods?

**Comment by Prototype2001** [comment]
KAS, Tac LS, Tweakscale, Scansat, MKS, Karbonite, Karbonite plus, FTT,USI Exploration pack.

Are you saying that when people load ore, water, substrate, chemicals, polymers, biomass and or substrate into their containers EL charges them more rocket parts?  It only charges me more if i put enriched uranium, depleted urandium, and or spare parts.

**Comment by BFlatt85** [comment]
After doing my own test I couldn't find an issue. I tested using a 2.5m kontainer from FTT. 
 Orbital Shipyard carrying on 1000 RocketParts (1st pic)
 Initial RocketPart cost of 300 (2nd pic)
 Finalized build kontainer appears to be filled with RocketParts (3rd pic)
 After clicking release button kontainer has only 700 RocketParts (4th pic)
http://imgur.com/a/vwf1O

**Comment by Prototype2001** [comment]
I posted this in the MKS thread but if you want to duplicate the issue its pretty simple.
[spoiler=1] [img]http://i.imgur.com/Lp41smZ.jpg[/img][/spoiler]  Craft file c3+ 1027 rocket parts, no survey stakes.

 [spoiler=2] This is a spoiler[img]http://i.imgur.com/rSTyddd.jpg[/img]  [/spoiler] Finished crafting test container of biomass & compost.

 [spoiler=3][img]http://i.imgur.com/wiJgB6M.jpg[/img][/spoiler] Full container

**Comment by BFlatt85** [comment]
Yeah I actually repro'd this last night. Building anything with fs switch will create resources out of thin air when using survey stations with or without survey stakes.

**Comment by Prototype2001** [comment]
I was also able to create the same outcomes using orbital shipyard and mobile launch platforms.
After hitting finilize you have a slider which you can move 0-100% if the slider is on any value other then 100% ( in pictures #2 & #4 the value is set to 0% creating completely filled containers of compost & biomass), resources will be generated inside the crafted containers.
http://imgur.com/a/orzOo#0

**Comment by BFlatt85** [comment]
This is where we differ. In my tests, it would appear to fill it completely. When I clicked the release button, it would fill it with what was left on the construction ship.

**Comment by Prototype2001** [comment]
Did you move the slider off 100% before hitting release?

**Comment by BFlatt85** [comment]
No, but I will try that tonight in the next couple hours.

**Comment by rabidninjawombat** [comment]
I was able to recreate this.

It only seems to happen on parts that have the fs switch module.  (and only when you move the transfer slider from 100% to any other number)  

Creating say just a normal fuel tank, does not cause this.

**Comment by taniwha-qf** [comment]
Actually, this might be an EL "bug": it could be that I am removing the resources too early: I remove them as soon as the vessel spawns, which means it occurs before modules are started (implying that MFT modified tanks will have issues too, though I haven't noticed any).

**Comment by Ramarren** [comment]
This is still a problem in Firespitter, it deletes all resource nodes and recreates them every time OnStart fires. As far as I can tell it is completely unnecessary, since once the proper part resource nodes are created there is not reason to touch them unless the tank setup is changed. I have patched FSfuelswitch to that effect: https://github.com/Ramarren/Firespitter/commit/a1951d2700a084d29d895897ac3aaee830a71cd3 , I haven't tested it very much yet, but it seems to fix this issue at least.

**Comment by taniwha** [comment]
Closing due to lack of complaints in the last 3 years.
