### ISSUE TITLE
Probe workshops

### ISSUE THREAD

**Issue by Kerbas-ad-astra** [taniwha/Extraplanetary-Launchpads#92]
I see the MM config has a comment that "Unfortunately, due to MM limitations, probe cores get a workshop too".  Maybe that was true at the time the patch was first made, but nowadays, this can be resolved by adding "~CrewCapacity[0]" to that patch's HAS[] block.

However, [as I indicated on the forum](http://forum.kerbalspaceprogram.com/threads/59545-0-90-Extraplanetary-Launchpads-v5-0-2?p=1721916&viewfull=1#post1721916), I'm interested in the possibility of totally automated construction (Von Neumann probes, advance missions preparing for Kerbal presence, cool stuff), so I think it would be cool to have a switch in the Workshop.DetermineProductivity method to give a probe core workshop (i.e. a workshop with no crew capacity) a productivity of 1 (as an example -- not as much as a highly-experienced engineer, or a team of engineers, but enough to get the job done).  The ExWorkshop module can then be handed out much more sparingly to probes (instead of all of them, using the patch modification above), only to, say, the size 2 and Mk2 probe core and the size 3 and 4 SpaceY probe cores.  Those are all late-game maximum-SAS-level cores, which seems like a reasonable restriction to me.

Alternatively, we could give the ExWorkshop module to all probe cores and add a check in the Workshop module code itself to make sure that the core is SASServiceLevel 3 before giving it any "kh".  This would allow maximum compatibility with all mods that add "super-smart" probe cores (Modular Rocket Systems comes to mind).

Thanks! What do you think?

**Comment by taniwha** [comment]
Fixed by 1a8c59bd0d5daa639756c7531e51c0152c82cf0a
