### ISSUE TITLE
Have a light on the stakes to make them more visible, also useful for nighttime

### ISSUE THREAD

**Issue by smjjames** [taniwha/Extraplanetary-Launchpads#93]
Just an idea since you have to hunt around with the mouse to find the stakes if you want to move them somewhere else again and they're really only visible within 20m of the stake.

**Comment by taniwha-qf** [comment]
This will have to wait until I can get light animation import/export working in my blender addon (https://github.com/taniwha-qf/io_object_mu).

**Comment by taniwha** [comment]
They now have a little plaque above them when the EL window is [left*] open.
* They retain the light even when switching vessels (eg, to a kerbal).
