### ISSUE TITLE
Ship spawns partially in ground, Build not finalized.

### ISSUE THREAD

**Issue by Thorbane** [taniwha/Extraplanetary-Launchpads#95]
The constructed vessel spawns partially in to ground, causing it to fly away, and the build does not complete correctly, allowing the spawning of more ships for free.

**Comment by Thorbane** [comment]
Actually the ship appears to spawn exactly where it should, and the teleport a meter lower for no reason whatsoever

**Comment by taniwha-qf** [comment]
It is very likely that there's an exception happening during spawn. I need your full log file.

**Comment by taniwha** [comment]
Closing due to lack of further information.
