### ISSUE TITLE
Cant craft ships that have a command module on it

### ISSUE THREAD

**Issue by PoscoM** [taniwha/Extraplanetary-Launchpads#96]
I am able to craft only rockets that doesn't have a manned command module on it. Whenever I try to finalize a ship that has a command moduled the UI for release doesn't show. This doesn't happen with unmaned ships. How can I solve this?

**Comment by taniwha-qf** [comment]
This sounds like a mod interaction problem  At this stage, prime suspects are ScienceAlert (it has a record) and RPM.

**Comment by taniwha** [comment]
closing due to lack of feedback
