### ISSUE TITLE
GitHub Release tagging

### ISSUE THREAD

**Issue by foonix** [taniwha/Extraplanetary-Launchpads#99]
I would like to update EPL automatically using [TinkerTime](https://github.com/oharaandrew314/TinkerTime/).  TT can download mods from their GitHub release page, but it uses the "Latest Release" tagging to decide which release to download.  As no EPL releases are tagged as latest, it doesn't work.  

Could the releases be tagged?  Please and thanks. :)

**Comment by taniwha-qf** [comment]
Releases are sorted (by time with newest at the top?). Not only that, but using numeric (instead of alpha) sort would put them in the right order. It sounds to me like TinkerTime needs to be smarter.

**Comment by foonix** [comment]
I think the idea is to allow beta or non-stable releases in the same list to be ignored.  Perhaps @oharaandrew314 could chime in?

**Comment by oharaandrew314** [comment]
@taniwha-qf doesn't release a compiled version of the mod on Github.  Nothing TinkerTime can do about that!
